config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to: "home#index"

resources :home
resources :profiles
resources :users
resources :contracts
resources :posts

end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contract.rb
class Contract < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/tutor.rb
class Tutor < User
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   def check_tutor(string)
     string.match(/tutor/)
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

protected

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:fname, :lname, :location, :phnumber, :usertype])
end

end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController

  def index
    @message ="Tutortorial Contract Page"
  end
  def email_send
    UserMailer.contact_email(@user).deliver_later
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @message ="Tutortorial Homepage"
    @User = User.last
  end

end

app/controllers/portals_controller.rb
class PortalsController < ApplicationController
  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json

  def show
  end

  # GET /posts/new
  def new
    # @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :subject, :content).merge({user_id: current_user.id})
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portal_helper.rb
module PortalHelper
end

app/helpers/portals_helper.rb
module PortalsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/index.html.erb
<div class="page_header">
  <%= @message %>
</div>

<nav>
  <% if (user_signed_in?) %>
  <!-- Add something here for the user to see after they login -->



  <% else %>

  <div id="logging">
    <!-- User Resistration Button -->
    <form action="/users/sign_up">
      <input type="submit"  id="button1" value="Register" />
    </form>
    <!-- <%= link_to 'Register', new_user_registration_path %> -->

    <!-- User Login Button -->
    <form action="/users/sign_in">
      <input type="submit"  id="button2" value="Login" />
    </form>
    <!-- <%= link_to 'Login', new_user_session_path %> -->
  <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutortorial</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="backimg">

    <div id="navbar">
      <div id="navbar2">
  			<ul>
  				<li id="home"><a href="/">Home</a></li>
          <% if !current_user || current_user.usertype == "Tutor" %>
    				<li id="tutors"><a href="#" class="dropbtn">Tutors</a>
    					<div class="drop_down_4all" id="drop_down_tutors">
              <% if not current_user %>
    						<div class="drop_down_tutors_sub">
      							<a href="/users/sign_up?t=Tutor">Register New</a>
    						</div>
              <% end %>
              <% if not current_user %>
              <% else %>
    						<div class="drop_down_tutors_sub">
    							<a href="/users/:id/edit">Edit Existing</a>
    						</div>
                <% end %>
                <% if not current_user %>
                <% else %>
      						<div class="drop_down_tutors_sub">
      							<a href="/">View All</a>
      						</div>
              <% end %>
    					</div>
            <% end %>
          <% if !current_user || current_user.usertype == "Student" %>
    				</li>
      				<li id="students"><a href="#" class="dropbtn">Students</a>
      					<div class="drop_down_4all" id="drop_down_students">
                  <% if not current_user %>
        						<div class="drop_down_students_sub">
        							<a href="/users/sign_up?t=Student">Register New</a>
        						</div>
                  <% end %>
                  <% if not current_user %>
                  <% else %>
        						<div class="drop_down_students_sub">
        							<a href="/students/edit">Edit Your Profile</a>
        						</div>
                  <% end %>
      					</div>
      				</li>
          <% end %>
          <li id="posts"><a href="#" class="dropbtn">Posts</a>
  					<div class="drop_down_4all" id="drop_down_posts">
  						<div class="drop_down_posts_sub">
  							<a href="/posts">View All</a>
  						</div>
              <div class="drop_down_posts_sub">
  							<a href="<%= edit_post_path(@post) if @post %>">Edit Existing</a>
  						</div>
  						<div class="drop_down_posts_sub">
  							<a href="<%= new_post_path %>">Create New</a>
  						</div>
  					</div>
  				</li>
          <% if current_user %>
            <li id="signout"><%= link_to 'Sign Out',  { :action=>"destroy", :controller=>"devise/sessions" }, method: :delete  %></li>
          <% end %>
  			</ul>
  		</div>
		</div>
    <br><br><br>

    <%= yield %>
    <span id="noticestyle">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </span>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/portal/show.html.erb
<div class="container">
  <div class="col-md-3 leftNav">
  </div>

  <div class="col-md-6 textEditor">
    <%= f.input :content, as: :wysihtml5, wysihtml5: { locale: "es-ES" } %>
  </div>

  <div class="col-md-3 rightbar">

  </div>

</div>

app/views/portals/show.html.erb
<div class="container">
  <div class="col-md-3 leftNav">
  </div>

  <div class="col-md-6 textEditor">
      <textarea id="some-textarea" class='wysihtml5' placeholder="Enter text ..."></textarea>

      <script type="text/javascript">
        $(document).ready(function(){

          $('.wysihtml5').each(function(i, elem) {
        $(elem).wysihtml5();
      });

      })
      </script>
  </div>

  <div class="col-md-3 rightbar">
    <%= instant_hangout %>
  </div>

</div

app/views/posts/_form.html.erb
<% post = Post.new %>
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="align_job3">
    <div class="field">
      <%= f.label :title, "Title:", :class => "labelStyle" %>
      <%= f.text_field :title, :class => "fieldStyle" %>
    </div>
    <div class="field">
      <%= f.label :subject, "Subject:", :class => "labelStyle" %>
      <%= f.text_field :subject, :class => "fieldStyle" %>
    </div>

    <div class="field">
      <%= f.label :content, "Content:", :class => "labelStyle" %>
      <%= f.text_area :content, :class => "fieldStyle" %>
    </div>

    <div class="actions">
      <%= f.submit "Submit", :class => "buttonJobSave2" %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<div class="align_job5">
  <%= link_to 'Show', @post %> |
  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div class="page_header">
  Posts
</div>
<br>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Subject</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |eapost| %>
      <tr>
        <td><%= eapost.title %></td>
        <td><%= eapost.subject %></td>
        <td><%= eapost.content %></td>
        <td><%= link_to 'Show', eapost %></td>
        <td><%= link_to 'Edit', edit_post_path(eapost) %></td>
        <td><%= link_to 'Destroy', eapost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 

app/views/posts/new.html.erb
<div class="page_header">
  New Post
</div>
<br>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="page_header">
  Posts
</div>
<br>
<p id="notice"><%= notice %></p>

<div class="align_job4">
  <span>
    <strong>Title:</strong>
    <%= @post.title %>
  </span>

  <p>
    <strong>Subject:</strong>
    <%= @post.subject %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= @post.content %>
  </p>
</div>

<div class="align_job5">
  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>